In [286]:
import numpy as np

# Input array
X = np.array([
  [1, 0, 1, 0],
  [1, 0, 1, 1],
  [0, 1, 0, 1]
])

# Output
y = np.array([
  [1],
  [1],
  [0]
])

In [287]:
# Sigmoid Function
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

# Derivative of Sigmoid Function
def derivatives_sigmoid(x):
  return x * (1 - x)

In [288]:
# Variable initialization
epoch = 10# Setting training iterations
lr = 0.1# Setting learning rate
inputlayer_neurons = X.shape[1]# number of features in data set
hiddenlayer_neurons = 3# number of hidden layers neurons
output_neurons = 1# number of neurons at output laye

In [289]:
# Variable initialization
epoch = 10000# Setting training iterations
lr = 0.1# Setting learning rate
inputlayer_neurons = X.shape[1]# number of features in data set
hiddenlayer_neurons = 3# number of hidden layers neurons
output_neurons = 1# number of neurons at output laye

In [290]:
# weight and bias initialization
#wh = np.random.uniform(size = (inputlayer_neurons, hiddenlayer_neurons))
wh = [[0.3551566,  0.84190762, 0.53471872],
 [0.36546163, 0.56467793, 0.60785994],
 [0.31807149, 0.87007041, 0.03385379],
 [0.63940456, 0.04343982, 0.10878098]]
print(wh)

[[0.3551566, 0.84190762, 0.53471872], [0.36546163, 0.56467793, 0.60785994], [0.31807149, 0.87007041, 0.03385379], [0.63940456, 0.04343982, 0.10878098]]


In [291]:
#bh = np.random.uniform(size = (1, hiddenlayer_neurons))
bh = [[0.27435179, 0.55661571, 0.31721594]]
print(bh)

[[0.27435179, 0.55661571, 0.31721594]]


In [292]:
#wout = np.random.uniform(size = (hiddenlayer_neurons, output_neurons))
wout = [[0.0287452 ],
 [0.37461094],
 [0.32445336]]
print(wout)

[[0.0287452], [0.37461094], [0.32445336]]


In [293]:
#bout = np.random.uniform(size = (1, output_neurons))
bout = [[0.08784717]]
print(bout)

[[0.08784717]]


for i in range(epoch):
  #Forward Propogation
  hidden_layer_input1 = np.dot(X, wh)
  hidden_layer_input = hidden_layer_input1 + bh
  hiddenlayer_activations = sigmoid(hidden_layer_input)
  output_layer_input1 = np.dot(hiddenlayer_activations, wout)
  output_layer_input = output_layer_input1 + bout
  output = sigmoid(output_layer_input)

  
  # Backpropagation
  E = y - output
  slope_output_layer = derivatives_sigmoid(output)
  slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
  d_output = E * slope_output_layer
  Error_at_hidden_layer = d_output.dot(wout.T)
  d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
  wout += hiddenlayer_activations.T.dot(d_output) * lr
  bout += np.sum(d_output, axis = 0, keepdims = True) * lr
  wh += X.T.dot(d_hiddenlayer) * lr
  bh += np.sum(d_hiddenlayer, axis = 0, keepdims = True) * lr

print(output)

### Epoch#1

In [294]:
hidden_layer_input1 = np.dot(X, wh)
print(hidden_layer_input1)

[[0.67322809 1.71197803 0.56857251]
 [1.31263265 1.75541785 0.67735349]
 [1.00486619 0.60811775 0.71664092]]


In [295]:
hidden_layer_input = hidden_layer_input1 + bh
print(hidden_layer_input)

[[0.94757988 2.26859374 0.88578845]
 [1.58698444 2.31203356 0.99456943]
 [1.27921798 1.16473346 1.03385686]]


In [296]:
hiddenlayer_activations = sigmoid(hidden_layer_input)
print(hiddenlayer_activations)

[[0.72062821 0.90624237 0.70802029]
 [0.83019141 0.90986876 0.72998952]
 [0.78231663 0.76219174 0.73766295]]


In [297]:
output_layer_input1 = np.dot(hiddenlayer_activations, wout)
print(output_layer_input1)

[[0.58992247]
 [0.60155836]
 [0.54735044]]


In [298]:
output_layer_input = output_layer_input1 + bout
print(output_layer_input)

[[0.67776964]
 [0.68940553]
 [0.63519761]]


In [299]:
output = sigmoid(output_layer_input)
print(output)

[[0.66324072]
 [0.66583467]
 [0.65366707]]


# Backpropagation

In [300]:
E = y - output
print(E)

[[ 0.33675928]
 [ 0.33416533]
 [-0.65366707]]


In [301]:
slope_output_layer = derivatives_sigmoid(output)
print(slope_output_layer)
slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
print(slope_hidden_layer)

[[0.22335247]
 [0.22249886]
 [0.22638643]]
[[0.20132319 0.08496714 0.20672756]
 [0.14097363 0.0820076  0.19710482]
 [0.17029732 0.18125549 0.19351632]]


In [302]:
d_output = E * slope_output_layer
print(d_output)

[[ 0.07521602]
 [ 0.07435141]
 [-0.14798136]]


In [310]:
Error_at_hidden_layer = d_output.dot(wout.T)
print(Error_at_hidden_layer)

[[ 0.00216331  0.02834992  0.02439183]
 [ 0.00213844  0.02802403  0.02411144]
 [-0.00425613 -0.05577614 -0.04798892]]


In [311]:
d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
print(d_hiddenlayer)

[[ 0.00043552  0.00240881  0.00504246]
 [ 0.00030146  0.00229818  0.00475248]
 [-0.00072481 -0.01010973 -0.00928664]]


In [312]:
wout += hiddenlayer_activations.T.dot(d_output) * lr
print(wout)

[[0.02877728]
 [0.3792157 ]
 [0.32412733]]


In [313]:
bout += np.sum(d_output, axis = 0, keepdims = True) * lr
print(bout)

[[0.08816438]]


In [314]:
wh += X.T.dot(d_hiddenlayer) * lr
print(wh)

[[0.35609721 0.84207403 0.53609283]
 [0.36423938 0.56451528 0.60644495]
 [0.3190121  0.87023682 0.0352279 ]
 [0.63867018 0.04332241 0.10807945]]


In [315]:
bh += np.sum(d_hiddenlayer, axis = 0, keepdims = True) * lr
print(bh)

[[0.27407015 0.55661947 0.31717506]]


In [316]:
print(output)

[[0.66324072]
 [0.66583467]
 [0.65366707]]


### Epoch#2

In [317]:
hidden_layer_input1 = np.dot(X, wh)
print(hidden_layer_input1)

[[0.6751093  1.71231084 0.57132073]
 [1.31377948 1.75563325 0.67940018]
 [1.00290956 0.60783769 0.7145244 ]]


In [318]:
hidden_layer_input = hidden_layer_input1 + bh
print(hidden_layer_input)

[[0.94917945 2.26893031 0.88849578]
 [1.58784962 2.31225272 0.99657523]
 [1.2769797  1.16445716 1.03169945]]


In [319]:
hiddenlayer_activations = sigmoid(hidden_layer_input)
print(hiddenlayer_activations)

[[0.72095013 0.90627096 0.70857966]
 [0.83031335 0.90988673 0.7303847 ]
 [0.78193522 0.76214166 0.73724524]]


In [320]:
output_layer_input1 = np.dot(hiddenlayer_activations, wout)
print(output_layer_input1)

[[0.59408919]
 [0.60567513]
 [0.55047938]]


In [321]:
output_layer_input = output_layer_input1 + bout
print(output_layer_input)

[[0.68225358]
 [0.69383952]
 [0.63864376]]


In [322]:
output = sigmoid(output_layer_input)
print(output)

[[0.66424149]
 [0.6668205 ]
 [0.65444682]]


# Backpropagation

In [323]:
E = y - output
print(E)

[[ 0.33575851]
 [ 0.3331795 ]
 [-0.65444682]]


In [324]:
slope_output_layer = derivatives_sigmoid(output)
print(slope_output_layer)
slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
print(slope_hidden_layer)

[[0.22302473]
 [0.22217092]
 [0.22614618]]
[[0.20118104 0.0849439  0.20649453]
 [0.14089309 0.08199287 0.19692289]
 [0.17051253 0.18128175 0.1937147 ]]


In [325]:
d_output = E * slope_output_layer
print(d_output)

[[ 0.07488245]
 [ 0.0740228 ]
 [-0.14800065]]


In [326]:
Error_at_hidden_layer = d_output.dot(wout.T)
print(Error_at_hidden_layer)

[[ 0.00215491  0.0283966   0.02427145]
 [ 0.00213017  0.02807061  0.02399281]
 [-0.00425906 -0.05612417 -0.04797105]]


In [327]:
d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
print(d_hiddenlayer)

[[ 0.00043353  0.00241212  0.00501192]
 [ 0.00030013  0.00230159  0.00472473]
 [-0.00072622 -0.01017429 -0.0092927 ]]


In [328]:
wout += hiddenlayer_activations.T.dot(d_output) * lr
print(wout)

[[0.02874945]
 [0.38145757]
 [0.32392858]]


In [329]:
bout += np.sum(d_output, axis = 0, keepdims = True) * lr
print(bout)

[[0.08825484]]


In [330]:
wh += X.T.dot(d_hiddenlayer) * lr
print(wh)

[[0.35617057 0.8425454  0.53706649]
 [0.36416676 0.56349785 0.60551568]
 [0.31908546 0.87070819 0.03620156]
 [0.63862757 0.04253514 0.10762265]]


In [331]:
bh += np.sum(d_hiddenlayer, axis = 0, keepdims = True) * lr
print(bh)

[[0.27407089 0.55607341 0.31721945]]


In [332]:
print(output)

[[0.66424149]
 [0.6668205 ]
 [0.65444682]]


### Epoch#3

In [333]:
hidden_layer_input1 = np.dot(X, wh)
print(hidden_layer_input1)

[[0.67525603 1.71325358 0.57326806]
 [1.3138836  1.75578872 0.68089071]
 [1.00279432 0.60603299 0.71313833]]


In [334]:
hidden_layer_input = hidden_layer_input1 + bh
print(hidden_layer_input)

[[0.94932692 2.26932699 0.89048751]
 [1.58795449 2.31186213 0.99811016]
 [1.27686521 1.1621064  1.03035778]]


In [335]:
hiddenlayer_activations = sigmoid(hidden_layer_input)
print(hiddenlayer_activations)

[[0.7209798  0.90630465 0.70899077]
 [0.83032812 0.9098547  0.73068685]
 [0.78191569 0.76171525 0.73698525]]


In [336]:
output_layer_input1 = np.dot(hiddenlayer_activations, wout)
print(output_layer_input1)

[[0.59610692]
 [0.6076328 ]
 [0.55177228]]


In [337]:
output_layer_input = output_layer_input1 + bout
print(output_layer_input)

[[0.68436176]
 [0.69588764]
 [0.64002713]]


In [338]:
output = sigmoid(output_layer_input)
print(output)

[[0.6647115 ]
 [0.66727538]
 [0.65475959]]


# Backpropagation

In [339]:
E = y - output
print(E)

[[ 0.3352885 ]
 [ 0.33272462]
 [-0.65475959]]


In [340]:
slope_output_layer = derivatives_sigmoid(output)
print(slope_output_layer)
slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
print(slope_hidden_layer)

[[0.22287012]
 [0.22201895]
 [0.22604947]]
[[0.20116793 0.08491653 0.20632286]
 [0.14088333 0.08201912 0.19678358]
 [0.17052354 0.18150513 0.19383799]]


In [341]:
d_output = E * slope_output_layer
print(d_output)

[[ 0.07472579]
 [ 0.07387117]
 [-0.14800806]]


In [342]:
Error_at_hidden_layer = d_output.dot(wout.T)
print(Error_at_hidden_layer)

[[ 0.00214833  0.02850472  0.02420582]
 [ 0.00212376  0.02817872  0.02392898]
 [-0.00425515 -0.05645879 -0.04794404]]


In [343]:
d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
print(d_hiddenlayer)

[[ 0.00043217  0.00242052  0.00499421]
 [ 0.0002992   0.00231119  0.00470883]
 [-0.0007256  -0.01024756 -0.00929338]]


In [344]:
wout += hiddenlayer_activations.T.dot(d_output) * lr
print(wout)

[[0.02869778]
 [0.3836772 ]
 [0.32371627]]


In [345]:
bout += np.sum(d_output, axis = 0, keepdims = True) * lr
print(bout)

[[0.08831373]]


In [346]:
wh += X.T.dot(d_hiddenlayer) * lr
print(wh)

[[0.35624371 0.84301857 0.5380368 ]
 [0.3640942  0.5624731  0.60458634]
 [0.3191586  0.87118136 0.03717187]
 [0.63858493 0.0417415  0.1071642 ]]


In [347]:
bh += np.sum(d_hiddenlayer, axis = 0, keepdims = True) * lr
print(bh)

[[0.27407147 0.55552182 0.31726042]]


In [348]:
print(output)

[[0.6647115 ]
 [0.66727538]
 [0.65475959]]


### Epoch#4

In [349]:
hidden_layer_input1 = np.dot(X, wh)
print(hidden_layer_input1)

[[0.67540231 1.71419993 0.57520867]
 [1.31398723 1.75594143 0.68237287]
 [1.00267912 0.6042146  0.71175054]]


In [350]:
hidden_layer_input = hidden_layer_input1 + bh
print(hidden_layer_input)

[[0.94947377 2.26972175 0.89246909]
 [1.5880587  2.31146325 0.99963329]
 [1.27675059 1.15973642 1.02901096]]


In [351]:
hiddenlayer_activations = sigmoid(hidden_layer_input)
print(hiddenlayer_activations)

[[0.72100934 0.90633817 0.70939944]
 [0.8303428  0.90982198 0.73098647]
 [0.78189615 0.76128482 0.7367241 ]]


In [352]:
output_layer_input1 = np.dot(hiddenlayer_activations, wout)
print(output_layer_input1)

[[0.5980768 ]
 [0.60953916]
 [0.55301589]]


In [353]:
output_layer_input = output_layer_input1 + bout
print(output_layer_input)

[[0.68639053]
 [0.69785289]
 [0.64132962]]


In [354]:
output = sigmoid(output_layer_input)
print(output)

[[0.6651635 ]
 [0.66771156]
 [0.65505396]]


# Backpropagation

In [355]:
E = y - output
print(E)

[[ 0.3348365 ]
 [ 0.33228844]
 [-0.65505396]]


In [356]:
slope_output_layer = derivatives_sigmoid(output)
print(slope_output_layer)
slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
print(slope_hidden_layer)

[[0.22272102]
 [0.22187283]
 [0.22595827]]
[[0.20115487 0.08488929 0.20615187]
 [0.14087363 0.08204594 0.19664525]
 [0.17053456 0.18173024 0.1939617 ]]


In [357]:
d_output = E * slope_output_layer
print(d_output)

[[ 0.07457513]
 [ 0.07372578]
 [-0.14801486]]


In [358]:
Error_at_hidden_layer = d_output.dot(wout.T)
print(Error_at_hidden_layer)

[[ 0.00214014  0.02861278  0.02414118]
 [ 0.00211577  0.0282869   0.02386623]
 [-0.0042477  -0.05678993 -0.04791482]]


In [359]:
d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
print(d_hiddenlayer)

[[ 0.0004305   0.00242892  0.00497675]
 [ 0.00029806  0.00232083  0.00469318]
 [-0.00072438 -0.01032045 -0.00929364]]


In [360]:
wout += hiddenlayer_activations.T.dot(d_output) * lr
print(wout)

[[0.02862326]
 [0.38587582]
 [0.32349126]]


In [361]:
bout += np.sum(d_output, axis = 0, keepdims = True) * lr
print(bout)

[[0.08834234]]


In [362]:
wh += X.T.dot(d_hiddenlayer) * lr
print(wh)

[[0.35631656 0.84349354 0.53900379]
 [0.36402176 0.56144105 0.60365698]
 [0.31923145 0.87165633 0.03813886]
 [0.63854229 0.04094154 0.10670415]]


In [363]:
bh += np.sum(d_hiddenlayer, axis = 0, keepdims = True) * lr
print(bh)

[[0.27407188 0.55496475 0.31729805]]


In [364]:
print(output)

[[0.6651635 ]
 [0.66771156]
 [0.65505396]]


### Epoch#5

In [365]:
hidden_layer_input1 = np.dot(X, wh)
print(hidden_layer_input1)

[[0.67554802 1.71514987 0.57714265]
 [1.31409031 1.75609141 0.68384681]
 [1.00256405 0.60238259 0.71036113]]


In [366]:
hidden_layer_input = hidden_layer_input1 + bh
print(hidden_layer_input)

[[0.9496199  2.27011463 0.8944407 ]
 [1.5881622  2.31105617 1.00114486]
 [1.27663594 1.15734735 1.02765918]]


In [367]:
hiddenlayer_activations = sigmoid(hidden_layer_input)
print(hiddenlayer_activations)

[[0.72103873 0.90637152 0.70980573]
 [0.83035738 0.90978858 0.73128361]
 [0.78187659 0.76085038 0.73646183]]


In [368]:
output_layer_input1 = np.dot(hiddenlayer_activations, wout)
print(output_layer_input1)

[[0.60000128]
 [0.61139681]
 [0.55421259]]


In [369]:
output_layer_input = output_layer_input1 + bout
print(output_layer_input)

[[0.68834362]
 [0.69973914]
 [0.64255492]]


In [370]:
output = sigmoid(output_layer_input)
print(output)

[[0.66559836]
 [0.66812993]
 [0.65533078]]


# Backpropagation

In [371]:
E = y - output
print(E)

[[ 0.33440164]
 [ 0.33187007]
 [-0.65533078]]


In [372]:
slope_output_layer = derivatives_sigmoid(output)
print(slope_output_layer)
slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
print(slope_hidden_layer)

[[0.22257718]
 [0.22173233]
 [0.22587235]]
[[0.20114188 0.08486219 0.20598156]
 [0.140864   0.08207332 0.19650789]
 [0.17054559 0.18195708 0.1940858 ]]


In [373]:
d_output = E * slope_output_layer
print(d_output)

[[ 0.07443018]
 [ 0.07358632]
 [-0.1480211 ]]


In [374]:
Error_at_hidden_layer = d_output.dot(wout.T)
print(Error_at_hidden_layer)

[[ 0.00213043  0.02872081  0.02407751]
 [ 0.00210628  0.02839518  0.02380453]
 [-0.00423685 -0.05711776 -0.04788353]]


In [375]:
d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
print(d_hiddenlayer)

[[ 0.00042852  0.00243731  0.00495952]
 [ 0.0002967   0.00233049  0.00467778]
 [-0.00072258 -0.01039298 -0.00929351]]


In [376]:
wout += hiddenlayer_activations.T.dot(d_output) * lr
print(wout)

[[0.02852683]
 [0.38805457]
 [0.32325442]]


In [377]:
bout += np.sum(d_output, axis = 0, keepdims = True) * lr
print(bout)

[[0.08834188]]


In [378]:
wh += X.T.dot(d_hiddenlayer) * lr
print(wh)

[[0.35638909 0.84397032 0.53996752]
 [0.3639495  0.56040175 0.60272762]
 [0.31930398 0.87213311 0.03910259]
 [0.63849971 0.04013529 0.10624258]]


In [379]:
bh += np.sum(d_hiddenlayer, axis = 0, keepdims = True) * lr
print(bh)

[[0.27407215 0.55440224 0.31733243]]


In [380]:
print(output)

[[0.66559836]
 [0.66812993]
 [0.65533078]]


In [381]:
epoch = 1100
for i in range(epoch):

    #Forward Propogation 
    hidden_layer_input1 = np.dot(X, wh) 
    hidden_layer_input = hidden_layer_input1 + bh 
    hiddenlayer_activations = sigmoid(hidden_layer_input) 
    output_layer_input1 = np.dot(hiddenlayer_activations, wout) 
    output_layer_input = output_layer_input1 + bout 
    output = sigmoid(output_layer_input)

    #Backpropagation
    E = y - output 
    slope_output_layer = derivatives_sigmoid(output) 
    slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations) 
    d_output = E * slope_output_layer 
    Error_at_hidden_layer = d_output.dot(wout.T) 
    d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer 
    wout += hiddenlayer_activations.T.dot(d_output) * lr 
    bout += np.sum(d_output, axis = 0, keepdims = True) * lr 
    wh += X.T.dot(d_hiddenlayer) * lr 
    bh += np.sum(d_hiddenlayer, axis = 0, keepdims = True) * lr

print(output)

[[0.938906  ]
 [0.8983458 ]
 [0.13993778]]
